language: php
php:
    - "7.4"
    - "8.0"
    - "8.1"
before_script:
    - "composer install"
    - "composer require php-coveralls/php-coveralls"
after_success:
    - "travis_retry php vendor/bin/php-coveralls -v"
